export type ElementBoxStyle = Pick<
	CSSStyleDeclaration,
	| "width"
	| "height"
	| "marginLeft"
	| "marginTop"
	| "marginRight"
	| "marginBottom"
	| "paddingLeft"
	| "paddingTop"
	| "paddingRight"
	| "paddingBottom"
	| "borderLeftWidth"
	| "borderLeftStyle"
	| "borderLeftColor"
	| "borderRightWidth"
	| "borderRightStyle"
	| "borderRightColor"
	| "borderTopWidth"
	| "borderTopStyle"
	| "borderTopColor"
	| "borderBottomWidth"
	| "borderBottomStyle"
	| "borderBottomColor"
	| "borderTopLeftRadius"
	| "borderTopRightRadius"
	| "borderBottomLeftRadius"
	| "borderBottomRightRadius"
>;
